version: '3'

services:
  app:
    container_name: elifuchsmanbe-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./bazel-bin:/app/bazel-bin
