version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV_TYPE=dev
    ports:
      - "8080:8000"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data

volumes:
  dynamodb-data:
