FROM golang:latest AS builder

WORKDIR /EliFuchsmanBE
COPY .env ./
COPY . ./

RUN go build -o EliFuchsmanBE

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache curl \
  && curl -o DynamoDBLocal.zip https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip \
  && unzip DynamoDBLocal.zip -d DynamoDBLocal_lib \
  && apk del curl


COPY --from=builder /EliFuchsmanBE/EliFuchsmanBE .

EXPOSE 8080
EXPOSE 8000

CMD ["./EliFuchsmanBE"]



